/*****************************************************************************
 * Copyright (c) 2009, 2021 CEA LIST, ARTAL.
 *
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Patrick Tessier (CEA LIST) Patrick.tessier@cea.fr - Initial API and implementation
 *  Etienne Allogo (ARTAL) - etienne.allogo@artal.fr - Bug 569174 : L1.2 declare overridable methods for annotation uniformization
 *****************************************************************************/
package org.eclipse.papyrus.uml.diagram.clazz.custom.edit.part;

import org.eclipse.draw2d.IFigure;
import org.eclipse.gmf.runtime.diagram.ui.editparts.AbstractBorderItemEditPart;
import org.eclipse.gmf.runtime.notation.View;
import org.eclipse.papyrus.infra.gmfdiag.common.editpart.IPapyrusEditPart;

/**
 * this a editpart to force the refresh after change the size of the border item
 */
public abstract class AbstractRedefinableTemplateSignatureEditPart extends AbstractBorderItemEditPart implements IPapyrusEditPart {

	public AbstractRedefinableTemplateSignatureEditPart(View view) {
		super(view);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected void refreshBounds() {
		super.refreshBounds();
		// ensure refreshing figures
		getFigure().getParent().getLayoutManager().layout(getFigure().getParent());
	}

	@Override
	protected void refreshVisuals() {
		super.refreshVisuals();
		refreshTransparency();
	}

	/**
	 *
	 * Returns the figure that represent the shape, this class is generated by the GMF tooling.
	 * 
	 * @return the figure
	 */
	protected abstract IFigure createNodePlate();

	/**
	 * Returns the figure that represent the shape, this class is generated by the GMF tooling.
	 * 
	 * @return the figure
	 */
	protected abstract IFigure createNodeShape();

	/**
	 * Installs the content pane in the node shape to add compartment for example.
	 *
	 * @param nodeShape
	 * @return the figure that is the the node shape
	 */
	protected abstract IFigure setupContentPane(IFigure nodeShape);
}