<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="buildertest" nsURI="http://www.eclipse.org/Papyrus/toolsmiths/test/BuilderTest"
    nsPrefix="test">
  <eClassifiers xsi:type="ecore:EClass" name="ToolingStuff">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ui" lowerBound="1" eType="#//UIStuff"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//AssociationStuff" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UIStuff">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssociationStuff">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ui" eType="#//UIStuff"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespace" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
